
import './globals.css'
import { Inter } from 'next/font/google'

import { Navigation } from './componets/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <style>{inter.styles}</style>
      </head>
      <body className={inter.className}>
        <Navigation />
        <div id="main-content">
          {children}
        </div>
      </body>
    </html>
  );
}

