import './globals.css';
import { Inter } from 'next/font/google';
import { Navigation } from './componets/Navigation';
import { Ubuntu } from 'next/font/google';

const font = Ubuntu({
  subsets: ['latin'], // Especifica el subconjunto deseado aquí
  preload: true, // Opcional: habilita o deshabilita el preloading según tus necesidades
  weight: ['400', '700'] // Corrección: cambia "weigth" a "weight"
});

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <style>{inter.styles}</style>
      </head>
      <body className={`${inter.className} ${font.className}`}>
        <Navigation />
        <div id="main-content">
          {children}
        </div>
      </body>
    </html>
  );
}
